version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - ${DB_PORT}:${DOCKER_DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DATABASE={DB_NAME}
    networks:
      - hyper-automation-chatbot-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: >
        /bin/sh -c "
        pg_isready -d ${DB_NAME} -U ${DB_USER}
        "      
      interval: 5s
      timeout: 5s
      retries: 5

  chatbot-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${USER_SERVER_PORT}:${USER_SERVER_PORT}"
      - "${USER_GRPC_SERVER_PORT}:${USER_GRPC_SERVER_PORT}"
    depends_on:
      - message-broker
      - postgres
    networks:
      - hyper-automation-chatbot-network
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DOCKER_DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DOCKER_DB_PASSWORD}
      - DB_NAME=${USER_DB_NAME}
    command: ./hyper_automatation_chatbot
    restart: always

volumes:
  postgres-data:

networks:
  hyper-automation-chatbot-network: