package rabbitmq

const WELCOME_NEW_EMPLOYEE_QUEUE = "WELCOME_NEW_EMPLOYEE_QUEUE"
const FILL_BUDDY_FORM_QUEUE = "FILL_BUDDY_FORM_QUEUE"
const CREATE_LEAVE_REQUEST_QUEUE = "CREATE_LEAVE_REQUEST_QUEUE"
const CREATE_INTEGRATE_TRAINING_REQUEST_QUEUE = "CREATE_INTEGRATE_TRAINING_REQUEST_QUEUE"
const HYPER_AUTOMATE_CHATBOT = "HYPER_AUTOMATE_CHATBOT"
